### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/BeautyPy#16]
- 'Similar packages in Python' this sections should also talk about how your function fit into the python or R ecosystem. What is the extension or what is the purpose of doing it? 

- The third function: calculate an image size is one or two line of code. Maybe adding more features on it.

- Messy file structure: I saw a test_compress.py under BeautyPy/BeautyPy/, where it should store function file.

- As we discussed in the lab, the proposal should contain not only function description but also input and output parameter type.

**Comment by jielinyu** [comment]
Thank you. We have solved all these four problems.
